version: '5.0'
services:
  redis:
    image: redis:latest
    ports:
      - "6543:6379"
    restart: unless-stopped
  
  etcd:
    image: gcr.io/etcd-development/etcd:v3.6.7
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=s1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=s1=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=tkn
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd-data:/etcd-data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    network_mode: host # share same network as host machine to get metrics from workers (scrape from localhost machine)
    # ports:
    #   - "9099:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./tgroups.json:/etc/prometheus/tgroups.json
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.listen-address=:9099'
    restart: unless-stopped

volumes:
  etcd-data: